# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'evtxrensic_form.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1153, 819)
        MainWindow.setStyleSheet(_fromUtf8(""))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.splitter_dashboard = QtGui.QSplitter(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_dashboard.sizePolicy().hasHeightForWidth())
        self.splitter_dashboard.setSizePolicy(sizePolicy)
        self.splitter_dashboard.setMinimumSize(QtCore.QSize(0, 0))
        self.splitter_dashboard.setSizeIncrement(QtCore.QSize(0, 0))
        self.splitter_dashboard.setBaseSize(QtCore.QSize(0, 0))
        self.splitter_dashboard.setAcceptDrops(False)
        self.splitter_dashboard.setAutoFillBackground(False)
        self.splitter_dashboard.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_dashboard.setObjectName(_fromUtf8("splitter_dashboard"))
        self.verticalLayoutWidget = QtGui.QWidget(self.splitter_dashboard)
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBox_3 = QtGui.QComboBox(self.verticalLayoutWidget)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.verticalLayout_2.addWidget(self.comboBox_3)
        self.label = QtGui.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.lineEdit = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.listWidget = QtGui.QListWidget(self.verticalLayoutWidget)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_2.addWidget(self.listWidget)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.listWidget_2 = QtGui.QListWidget(self.verticalLayoutWidget)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.label_4 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_2.addWidget(self.label_4)
        self.listWidget_3 = QtGui.QListWidget(self.verticalLayoutWidget)
        self.listWidget_3.setObjectName(_fromUtf8("listWidget_3"))
        self.verticalLayout_2.addWidget(self.listWidget_3)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.splitter_dashboard)
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.toolButton_3 = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName(_fromUtf8("toolButton_3"))
        self.horizontalLayout.addWidget(self.toolButton_3)
        self.toolButton_2 = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName(_fromUtf8("toolButton_2"))
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.toolButton = QtGui.QToolButton(self.verticalLayoutWidget_2)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout.addWidget(self.toolButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.graphicsView = QtGui.QGraphicsView(self.verticalLayoutWidget_2)
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))
        self.verticalLayout_3.addWidget(self.graphicsView)
        self.gridLayout_4.addWidget(self.splitter_dashboard, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/resource/dashboard.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox = QtGui.QComboBox(self.tab_2)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.comboBox_2 = QtGui.QComboBox(self.tab_2)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.progressBar = QtGui.QProgressBar(self.tab_2)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.splitter_loglist = QtGui.QSplitter(self.tab_2)
        self.splitter_loglist.setOrientation(QtCore.Qt.Vertical)
        self.splitter_loglist.setObjectName(_fromUtf8("splitter_loglist"))
        self.treeWidget = QtGui.QTreeWidget(self.splitter_loglist)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setCascadingSectionResizes(True)
        self.treeWidget.header().setDefaultSectionSize(100)
        self.treeWidget.header().setHighlightSections(True)
        self.tableWidget_listpanel = QtGui.QTableWidget(self.splitter_loglist)
        self.tableWidget_listpanel.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_listpanel.setAlternatingRowColors(True)
        self.tableWidget_listpanel.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableWidget_listpanel.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableWidget_listpanel.setTextElideMode(QtCore.Qt.ElideRight)
        self.tableWidget_listpanel.setObjectName(_fromUtf8("tableWidget_listpanel"))
        self.tableWidget_listpanel.setColumnCount(7)
        self.tableWidget_listpanel.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_listpanel.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_listpanel.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_listpanel.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_listpanel.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_listpanel.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidget_listpanel.setHorizontalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_listpanel.setHorizontalHeaderItem(6, item)
        self.tableWidget_listpanel.verticalHeader().setDefaultSectionSize(23)
        self.tableWidget_listpanel.verticalHeader().setSortIndicatorShown(False)
        self.verticalLayout.addWidget(self.splitter_loglist)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/resource/list.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon1, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1153, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuOption = QtGui.QMenu(self.menubar)
        self.menuOption.setObjectName(_fromUtf8("menuOption"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/resource/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setWhatsThis(_fromUtf8(""))
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionTimezone = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/resource/timezone.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTimezone.setIcon(icon3)
        self.actionTimezone.setObjectName(_fromUtf8("actionTimezone"))
        self.action_3 = QtGui.QAction(MainWindow)
        self.action_3.setObjectName(_fromUtf8("action_3"))
        self.actionEvtxrensic = QtGui.QAction(MainWindow)
        self.actionEvtxrensic.setObjectName(_fromUtf8("actionEvtxrensic"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icon/resource/exit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon4)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionEvtxrensic)
        self.menuOption.addAction(self.action_3)
        self.menuOption.addSeparator()
        self.menuOption.addAction(self.actionTimezone)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuOption.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "evtxrensic", None))
        self.label.setText(_translate("MainWindow", "검색", None))
        self.label_2.setText(_translate("MainWindow", "TextLabel", None))
        self.label_3.setText(_translate("MainWindow", "TextLabel", None))
        self.label_4.setText(_translate("MainWindow", "TextLabel", None))
        self.toolButton_3.setText(_translate("MainWindow", "어떤기능 1", None))
        self.toolButton_2.setText(_translate("MainWindow", "어떤기능 2", None))
        self.toolButton.setText(_translate("MainWindow", "어떤기능 3", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Dash Board", None))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "test", None))
        self.treeWidget.headerItem().setText(1, _translate("MainWindow", "test2", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "test", None))
        self.treeWidget.topLevelItem(0).setText(1, _translate("MainWindow", "hello", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.tableWidget_listpanel.setSortingEnabled(True)
        item = self.tableWidget_listpanel.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "레코드 번호", None))
        item = self.tableWidget_listpanel.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "로그 시간", None))
        item = self.tableWidget_listpanel.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "수준", None))
        item = self.tableWidget_listpanel.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "이벤트 공급자", None))
        item = self.tableWidget_listpanel.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "이벤트 ID", None))
        item = self.tableWidget_listpanel.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "작업 범주", None))
        item = self.tableWidget_listpanel.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "정보", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Log List", None))
        self.menuFile.setTitle(_translate("MainWindow", "파일", None))
        self.menuHelp.setTitle(_translate("MainWindow", "도움말", None))
        self.menuOption.setTitle(_translate("MainWindow", "로그 분석", None))
        self.actionOpen.setText(_translate("MainWindow", "열기", None))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O", None))
        self.actionTimezone.setText(_translate("MainWindow", "타임 존 설정", None))
        self.action_3.setText(_translate("MainWindow", "그래프 분석", None))
        self.actionEvtxrensic.setText(_translate("MainWindow", "evtxrensic 정보", None))
        self.actionExit.setText(_translate("MainWindow", "닫기", None))

import resources_rc
